force-app/main/default/objects/Doctor_Facility_Assignment__c/Doctor_Facility_Assignment__c.object-meta.xml
<CustomObject>
    <label>Doctor Facility Assignment</label>
    <nameField>
        <displayFormat>DFA-{0000}</displayFormat>
        <label>Doctor_Facility_Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Doctor Facility Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Doctor_Facility_Assignment__c/fields/Medical_Facility__c.field-meta.xml
<CustomField>
    <fullName>Medical_Facility__c</fullName>
    <label>Medical Facility</label>
    <referenceTo>Medical_Facility__c</referenceTo>
    <relationshipLabel>Doctor Facility Assignments</relationshipLabel>
    <relationshipName>Doctor_Facility_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Doctor_Facility_Assignment__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <label>Person</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Person__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Doctor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Doctor Facility Assignments</relationshipLabel>
    <relationshipName>Doctor_Facility_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Medical_Facility__c/Medical_Facility__c.object-meta.xml
<CustomObject>
    <label>Medical Facility</label>
    <nameField>
        <label>Medical Facility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medical Facilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <label>Person</label>
    <nameField>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Person__c/fields/Specialization__c.field-meta.xml
<CustomField>
    <fullName>Specialization__c</fullName>
    <label>Specialization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Internist</fullName>
            </value>
            <value>
                <fullName>Cardiologist</fullName>
            </value>
            <value>
                <fullName>Allergist</fullName>
            </value>
            <value>
                <fullName>Laryngologist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AppointmentController.cls
public with sharing class AppointmentController {
    @AuraEnabled(cacheable=true)
    public static List<SObject> getAvailableDoctors(Id facilityId, String specialization) {
        List<Doctor_Facility_Assignment__c> assignments = [
            SELECT Person__r.Id, Person__r.Name 
            FROM Doctor_Facility_Assignment__c 
            WHERE Medical_Facility__c = :facilityId 
            AND Person__r.Specialization__c = :specialization
            ORDER BY Person__r.Name ASC
        ];
        List<SObject> doctors = new List<SObject>();
        for(Doctor_Facility_Assignment__c dfa : assignments) {
            doctors.add(dfa.Person__r);
        }
        
        return doctors;
    }
}